### ISSUE TITLE
[Vote], whether to support freemind

### ISSUE THREAD

**Issue by sgalcheung** [Lruihao/kityminder-core#1]
Freemind is only an open-source mind map, and its format is .mm it is XML content.

and also the kityminder provides the [Freemind protocol](https://github.com/fex-team/kityminder/blob/dev/src/protocol/freemind.js)

What we know so far is that the Feishu export mind map is in the .mm format.

Welcome to add or make suggestions.

**Comment by Lruihao** [comment]
![image](https://github.com/Lruihao/kityminder-core/assets/33419593/c8bec8c6-64e6-4fdb-9075-29afd15a43ad)

按照原来百度脑图的思路，我觉得第三方格式的导入导出应该由上层应用来构建以避免核心的冗余。

另外我 fork 这个仓库的目的是为了必要情况下修复一些原项目留下的 bug，并没打算新增功能。😂

**Comment by sgalcheung** [comment]
确实是如此，kitymind-core 项目是基于 json 来做解析的，其他的格式被称作本地格式，可以注册新的协议，并将数据转为json，详细的请参考导入[导出功能设计](https://github.com/fex-team/kityminder/blob/dev/doc/Import%20Export.md#%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E5%8A%9F%E8%83%BD%E8%AE%BE%E8%AE%A1)
